name: Dotenv file
description: Creates a dotenv file for environment variables

runs:
  using: composite
  steps:
    - name: Make envfile
      uses: SpicyPizza/create-envfile@v1
      with:
        envkey_STAGE: ${{ secrets.STAGE }}
        file_name: .env
