name: Deploy the code to the development stage

on:
  push:
    branches:
      - development

jobs:
  development-build:
    name: development-build
    environment: Development
    needs: [format, lint, test]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/prepare
      - name: Create dotenv file
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_STAGE: ${{ secrets.STAGE }}
          file_name: .env
      - run: yarn build
      - name: Deploy to development stage
        uses: serverless/github-action@v3
        with:
          args: deploy --stage dev
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
