name: Deploy the code to the staging stage

on:
  push:
    branches:
      - staging

jobs:
  staging-build:
    name: staging-build
    environment: Staging
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/prepare
      - name: Create dotenv file
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_STAGE: ${{ secrets.STAGE }}
          file_name: .env
      - run: yarn build
      - name: Deploy to staging stage
        uses: serverless/github-action@v3
        with:
          args: deploy --stage stg
        env:
          NODE_ENV: staging
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
