name: Run unit and integration tests

on:
  push:
    branches:
      - main
      - staging
      - development
  pull_request:
    branches:
      - main
      - staging
      - development

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/prepare
      - run: yarn docker:detach
      # - name: Setup DynamoDB Local
      #   uses: rrainn/dynamodb-action@v2.0.1
      #   with:
      #     dbPath: /home/dynamodblocal/data/
      #     port: 8000
      #     cors: '*'
      - run: yarn test
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
